language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer require atoum/atoum
  - if [[ "$(php -v | grep 'PHP 5')" ]]; then echo yes | pecl install apcu-4.0.8; fi
  - if [[ "$(php -v | grep 'PHP 7')" ]]; then echo yes | pecl install apcu; fi
  #- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-add tests/apc.ini

script: vendor/bin/atoum -c tests/.atoum.php
